### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by tleibert** [tkaitchuck/aHash#155]
Does aHash still support no_std? I've set the following flags 
```toml
[dependencies]
ahash = { version = "0.8.3", default-features = false, features = ["compile-time-rng"] }
```
but compilation fails as `ahash` still pulls in `once_cell`, which doesn't support no_std.
