### ISSUE TITLE
Can't get `compile-time-rng`/`no-rng` features to work

### ISSUE THREAD

**Issue by bpandreotti** [tkaitchuck/aHash#161]
For my use case, I need deterministic hash maps/sets, but I can't seem to get the `compile-time-rng` or `no-rng` features to work in `ahash`. My Cargo.toml looks like this:

```toml
[package]
name = "determinism-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = { version = "0.8.3", default-features = false, features = ["std", "compile-time-rng"] }
```

and when I run the following code, the hash value is always different:

```rust
fn main() {
    let s = RandomState::default();
    println!("{}", s.hash_one("foo"));
}
```

The same is true if I use the `no-rng` feature instead of `compile-time-rng`, or if I fix the `CONST_RANDOM_SEED` environment variable.
