### ISSUE TITLE
Cannot use ahash with wasm32-unknown-unknown builds

### ISSUE THREAD

**Issue by tylers-epilog** [tkaitchuck/aHash#276]
When I try to build with a target of wasm32-unknown-unknown, I get compile errors from the getrandom dependency. This occurs because getrandom needs the wasm_js feature enabled to work on that target.

Perhaps it would be suitable to change the getrandom dependency to the following?

```
[target.'cfg(not(all(target_arch = "wasm32", target_vendor = "unknown", target_os = "unknown")))'.dependencies.getrandom]
version = "0.3"
optional = true
[target.'cfg(all(target_arch = "wasm32", target_vendor = "unknown", target_os = "unknown"))'.dependencies.getrandom]
version = "0.3"
features = ["wasm_js"]
optional = true
```

Thanks!

**Comment by zhiburt** [comment]
Hi there
I guess I've got a similar issue

```rust
error: The wasm32-unknown-unknown targets are not supported by default; you may need to enable the "wasm_js" configuration flag. Note that enabling the `wasm_js` feature flag alone is insufficient. For more information see: https://docs.rs/getrandom/0.3.3/#webassembly-support
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/getrandom-0.3.3/src/backends.rs:168:9
    |
168 | /         compile_error!(concat!(
169 | |             "The wasm32-unknown-unknown targets are not supported by default; \
170 | |             you may need to enable the \"wasm_js\" configuration flag. Note \
171 | |             that enabling the `wasm_js` feature flag alone is insufficient. \
172 | |             For more information see: \
173 | |             https://docs.rs/getrandom/", env!("CARGO_PKG_VERSION"), "/#webassembly-support"
174 | |         ));
    | |__________^

```

**Comment by schungx** [comment]
I am wondering if this issue will be addressed.  Bumping `getrandom` to 0.3 should technically be breaking, necessitating a major version bump.

**Comment by tylers-epilog** [comment]
I did eventually get things to build. The process for getting it working is all there in `getrandom`'s documentation, though it seemed a bit scattered about.

Make a `config.toml` file in project directory:
```toml
[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
```

And include the `getrandom` dependency in your `Cargo.toml` file even if you don't directly depend on it:
```toml
[target.'cfg(target_arch = "wasm32")'.dependencies]
# getrandom-2 = { package = "getrandom", version = "0.2", features = ["js"] } # You may or may not need this
getrandom-3 = { package = "getrandom", version = "0.3", features = ["wasm_js"] }
```

I can close this ticket if others find that it fixes their issue as well.
